=== jappa/VizStack/share/schema/displayconfig.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.hp.com"
xmlns="http://www.hp.com"
elementFormDefault="qualified" >

<xs:element name="display">
	<xs:complexType>
		<xs:sequence>
			<!-- Mandatory name comes first. This is the dentifying name of the model. -->
			<xs:element name="model" type="xs:string" />

			<!-- 

			The type of input this display device takes by default. 
			If the device connectes using a digital interface, then use "digital". All flat panels will be by default digital.
			Digital interfaces are connected using either DVI-D or "DisplayPort". Avoid usage of DVI-I cables. This may make the GPU
			switch to using analog signals.
			If the device connects using a VGA cable, use "analog". All CRT displays are analog.
			-->
			<xs:element name="input" > 
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="digital" />
						<xs:enumeration value="analog" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<!-- 

			If you can get the EDID for this device, then use it here. Else be prepared to specify
			modelines

			-->
			<xs:element name="edid" minOccurs="0" maxOccurs="1" type="xs:string" />

			<!-- If you have the EDID bytes, feel free to use them too! -->
			<xs:element name="edidBytes" minOccurs="0" maxOccurs="1" type="xs:string" />

			<!-- This name should match the name exposed in the EDID -->
			<xs:element name="edid_name" type="xs:string" minOccurs="0" maxOccurs="1" />

			<xs:element name="hsync" minOccurs="0" maxOccurs="1" > <!-- If EDID is not specified, the sync value will be used from this -->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="min" type="xs:string" />
						<xs:element name="max" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="vrefresh" minOccurs="0" maxOccurs="1" > <!-- If EDID is not specified, the sync value will be used from this -->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="min" type="xs:string" />
						<xs:element name="max" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="dimensions" minOccurs="0" maxOccurs="1"> <!-- physical dimensions of the display -->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="width" type="xs:float" /> <!-- width in mm -->
						<xs:element name="height" type="xs:float" /> <!-- height in mm -->
						<xs:element name="bezel" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="left" type="xs:float" />
									<xs:element name="right" type="xs:float" />
									<xs:element name="bottom" type="xs:float" />
									<xs:element name="top" type="xs:float" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="default_mode" type="xs:string" /> <!-- The default mode to choose if none is specified. Must be in the list below -->

			<xs:element name="mode" minOccurs="0" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:sequence>
						<xs:element name="type" type="xs:string" />
						<xs:element name="alias" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
						<xs:element name="width" type="xs:nonNegativeInteger" />
						<xs:element name="height" type="xs:nonNegativeInteger" />
						<xs:element name="refresh" type="xs:nonNegativeInteger" />
						<xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="1" /> <!-- value depends on 'type'. Can be a modeline or empty at this point -->
						<xs:element name="bezel" minOccurs="0" maxOccurs="1"> <!-- per resolution bezel, in pixels -->
							<xs:complexType>
								<xs:sequence>
									<xs:element name="left" type="xs:nonNegativeInteger" /> <!-- note : all values in pixels. Any value specified here will override the computed bezel -->
									<xs:element name="right" type="xs:nonNegativeInteger" />
									<xs:element name="bottom" type="xs:nonNegativeInteger" />
									<xs:element name="top" type="xs:nonNegativeInteger" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== jappa/VizStack/share/templates/displays/Sony-SRX.xml
<?xml version="1.0" ?>

<!--

Sony SRX

This projector takes 4xDVI inputs, each capable of 2048x1080 resolution for an overall
projector resolution of 4096x2160 !

All Established, Standard and Detailed Timings from the EDID are included as
valid modes, though one may not be interested in running at anything less than
2048x1080 @ 60 Hz !

FIXME: add the stereo modes here.
-->

<display
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>Sony SRX PJ</model>
	<input>digital</input>
	<edid>/opt/vizstack/share/templates/displays/edids/Sony-SRX-PJ.bin</edid>
	<edid_name>Sony SRX PJ</edid_name>
	<default_mode>2048x1080_60</default_mode>
	<mode>
		<type>edid</type> 
		<alias>2048x1080_60</alias> 
		<alias>2048x1080</alias> 
		<width>2048</width>
		<height>1080</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type> 
		<alias>2048x1080_24</alias>
		<width>2048</width>
		<height>1080</height>
		<refresh>24</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1600x1200_60</alias>
		<width>1600</width>
		<height>1200</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1400x1050_60</alias>
		<width>1400</width>
		<height>1050</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1280x1024_60</alias>
		<width>1280</width>
		<height>1024</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1280x960_60</alias>
		<width>1280</width>
		<height>960</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1024x768_60</alias>
		<width>1024</width>
		<height>768</height>
		<refresh>60</refresh>
	</mode>
</display>

=== jappa/VizStack/share/templates/displays/LPL-LPL.xml
<?xml version="1.0" ?>

<!--

LPL is Shree's Laptop's (DV 2000 series) display

According to the EDID, manufacturer is "LPL", and monitor name is "LPL" too !

-->

<display
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>HP DV 2000 Laptop Display</model>
	<input>digital</input>
	<edid>/opt/vizstack/share/templates/displays/edids/LPL-LPL.bin</edid>
	<edid_name>LPL</edid_name>
	<default_mode>1280x800_60</default_mode>
	<mode>
		<type>edid</type>
		<alias>1280x800_60</alias>
		<alias>1280x800</alias>
		<width>1280</width>
		<height>800</height>
		<refresh>60</refresh>
	</mode>
</display>

=== jappa/VizStack/share/templates/displays/Dell-3008WFP.xml
<?xml version="1.0" ?>
<!--
Dell 3008WFP Monitor

30 inch widescreen flat panel monitor. Template courtesy Simon Fowler(CSIRO).

The bezels were measured by hand.
-->

<display
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>Dell 3008WFP</model>
	<input>digital</input>
	<edid>/opt/vizstack/share/templates/displays/edids/Dell-3008WFP.bin</edid>
	<edid_name>Dell 3008WFP</edid_name>
	<dimensions>
		<width>650</width> <!-- you get this from the "Maximum Image" size on the EDID -->
		<height>410</height>
		<bezel><!-- Quickspecs says overall size is 692 x 455 -->
			<left>27</left> 
			<right>27</right>
			<bottom>27</bottom>
			<top>30</top>
		</bezel>
	</dimensions>
	<default_mode>2560x1600_60</default_mode>
	<mode>
		<type>edid</type>
		<alias>2560x1600_60</alias>
		<alias>2560x1600</alias>
		<width>2560</width>
		<height>1600</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1920x1200_60</alias>
		<alias>1920x1200</alias>
		<width>1920</width>
		<height>1200</height>
		<refresh>60</refresh>
	</mode>
</display>

=== jappa/VizStack/share/templates/displays/HP-L1955.xml
<?xml version="1.0" ?>

<!--

L1955

19" TFT monitor from HP.

-->

<display
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>HP L1955</model>
	<input>analog</input> <!-- The L1955 has a DVI-I and a VGA input. It ships with a VGA cable only, and that's how many end up using it. Hence this choice ! -->
	<edid>/opt/vizstack/share/templates/displays/edids/HP-L1955.bin</edid>
	<edid_name>HP L1955</edid_name>
	<default_mode>1280x1024_60</default_mode>
	<mode>
		<type>edid</type>
		<alias>1280x1024_60</alias>
		<alias>1280x1024</alias> <!-- default refresh rate 60 Hz -->
		<width>1280</width>
		<height>1024</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1280x1024_75</alias>
		<width>1280</width>
		<height>1024</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1152x864_75</alias>
		<width>1152</width>
		<height>864</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1024x768_75</alias>
		<width>1024</width>
		<height>768</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1024x768_70</alias>
		<width>1024</width>
		<height>768</height>
		<refresh>70</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1024x768_60</alias>
		<alias>1024x768</alias>
		<width>1024</width>
		<height>768</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>800x600_75</alias>
		<width>800</width>
		<height>600</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>800x600_72</alias>
		<width>800</width>
		<height>600</height>
		<refresh>72</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>800x600_60</alias>
		<alias>800x600</alias>
		<width>800</width>
		<height>600</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>640x480_75</alias>
		<width>640</width>
		<height>480</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>640x480_72</alias>
		<width>640</width>
		<height>480</height>
		<refresh>72</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>640x480_60</alias>
		<width>640</width>
		<height>480</height>
		<refresh>60</refresh>
	</mode>
</display>

=== jappa/VizStack/share/templates/displays/generic-stereo-CRT.xml
<?xml version="1.0" ?>

<display
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>Generic Stereo CRT</model>
	<input>analog</input>
	<hsync>
		<min>30</min>
		<max>150</max>
	</hsync>
	<vrefresh>
		<min>50</min>
		<max>120</max>
	</vrefresh>
	<default_mode>1280x1024_110</default_mode>
	<!-- All modelines generated by GTF. Differ in some decimal digits from the SVA modelines !-->
	<mode>
		<type>modeline</type>
		<alias>1280x1024_110</alias>
		<width>1280</width>
		<height>1024</height>
		<refresh>110</refresh>
		<value>211.22  1280 1376 1520 1760  1024 1025 1028 1091 -HSync +Vsync</value> <!-- 1280x1024 @ 110.00 Hz (GTF) hsync: 120.01 kHz; pclk: 211.22 MHz -->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1920x1200_110</alias>
		<width>1920</width>
		<height>1200</height>
		<refresh>110</refresh>
		<value>373.38  1920 2072 2288 2656  1200 1201 1204 1278  -HSync +Vsync</value> <!-- 1920x1200 @ 110.00 Hz (GTF) hsync: 140.58 kHz; pclk: 373.38 MHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1400x1050_110</alias>
		<width>1400</width>
		<height>1050</height>
		<refresh>110</refresh>
		<value>237.32  1400 1512 1664 1928  1050 1051 1054 1119  -HSync +Vsync</value> <!-- 1400x1050 @ 110.00 Hz (GTF) hsync: 123.09 kHz; pclk: 237.32 MHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1280x960_110</alias>
		<width>1280</width>
		<height>960</height>
		<refresh>110</refresh>
		<value>198.05  1280 1376 1520 1760  960 961 964 1023  -HSync +Vsync</value> <!-- 1280x960 @ 110.00 Hz (GTF) hsync: 112.53 kHz; pclk: 198.05 MHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1152x900_110</alias>
		<width>1152</width>
		<height>900</height>
		<refresh>110</refresh>
		<value>167.10  1152 1240 1368 1584  900 901 904 959  -HSync +Vsync</value> <!-- 1152x900 @ 110.00 Hz (GTF) hsync: 105.49 kHz; pclk: 167.10 MHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1024x768_110</alias>
		<width>1024</width>
		<height>768</height>
		<refresh>110</refresh>
		<value>125.41 1024 1096 1208 1392  768 769 772 819  -HSync +Vsync</value> <!-- 1024x768 @ 110.00 Hz (GTF) hsync: 90.09 kHz; pclk: 125.41 MHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>800x600_60</alias>
		<width>800</width>
		<height>600</height>
		<refresh>110</refresh>
		<value>75.47  800 848 936 1072  600 601 604 640  -HSync +Vsync</value> <!-- 800x600 @ 110.00 Hz (GTF) hsync: 70.40 kHz; pclk: 75.47 MHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>640x480_60</alias>
		<width>640</width>
		<height>480</height>
		<refresh>110</refresh>
		<value>47.76  640 680 744 848  480 481 484 512  -HSync +Vsync</value> <!-- 640x480 @ 110.00 Hz (GTF) hsync: 56.32 kHz; pclk: 47.76 MHz !-->
	</mode>
</display>

=== jappa/VizStack/share/templates/displays/HP-AVO-SmartCable.xml
<?xml version="1.0" ?>

<!--

The AVO smart cable is the dongle with which we connect the graphics cards
to the KVM.

-->

<display
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>AVO Smart Cable</model>
	<input>analog</input>
	<edid>/opt/vizstack/share/templates/displays/edids/HP-AVO-SmartCable.bin</edid>
	<edid_name>AVO Smart Cable</edid_name>
	<default_mode>1024x768_60</default_mode>
	<mode>
		<type>edid</type> 
		<alias>1024x768_60</alias>
		<alias>1024x768</alias> <!-- default 1024x768. Runs at 60 Hz for max compatibility with RKM -->
		<width>1024</width>
		<height>768</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type> 
		<alias>1024x768_75</alias>
		<width>1024</width>
		<height>768</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type> 
		<alias>1280x1024_75</alias>
		<width>1280</width>
		<height>1024</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type> 
		<alias>1280x1024_60</alias>
		<alias>1280x1024</alias> <!-- default 1280x1024. Runs at 60 Hz for max compatibility with RKM -->
		<width>1280</width>
		<height>1024</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1280x960_75</alias>
		<width>1280</width>
		<height>960</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1280x960_60</alias>
		<alias>1280x960</alias>
		<width>1280</width>
		<height>960</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type> 
		<alias>1152x864_75</alias>
		<width>1152</width>
		<height>864</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type> 
		<alias>1152x864_70</alias>
		<width>1152</width>
		<height>864</height>
		<refresh>75</refresh>
	</mode>
	<mode>
		<type>edid</type> 
		<alias>1152x864_60</alias>
		<alias>1152x864</alias>
		<width>1152</width>
		<height>864</height>
		<refresh>60</refresh>
	</mode>
</display>

=== jappa/VizStack/share/templates/displays/HP-LP2065.xml
<?xml version="1.0" ?>

<!--

LP2065 is HP's standard 20 inch TFT monitor 

The standard resolution of this device is 1600x1200 @ 60 Hz.

-->

<display
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>HP LP2065</model>
	<input>digital</input>
	<edid>/opt/vizstack/share/templates/displays/edids/HP-LP2065.bin</edid>
	<edid_name>HP LP2065</edid_name>
	<dimensions>
		<width>410</width> <!-- you get this from the "Maximum Image size" on the EDID -->
		<height>310</height>
		<bezel><!-- Quickspecs says overall size is 443 x 345 -->
			<left>16.5</left> 
			<right>16.5</right>
			<bottom>17.5</bottom>
			<top>17.5</top>
		</bezel>
	</dimensions>
	<default_mode>1600x1200_60</default_mode>
	<mode>
		<type>edid</type>
		<alias>1600x1200_60</alias>
		<alias>1600x1200</alias> <!-- With 60 Hz default -->
		<width>1600</width>
		<height>1200</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1280x1024_60</alias>
		<alias>1280x1024</alias> <!-- 60 Hz is default -->
		<width>1280</width>
		<height>1024</height>
		<refresh>60</refresh>
	</mode>
</display>

=== jappa/VizStack/share/templates/displays/generic-DFP.xml
<?xml version="1.0" ?>

<display
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>Generic DFP Monitor</model>
	<input>digital</input>
	<hsync>
		<min>30</min>
		<max>150</max>
	</hsync>
	<vrefresh>
		<min>50</min>
		<max>120</max>
	</vrefresh>
	<default_mode>1280x1024_60</default_mode>
	<!-- All modelines generated below from "umc <hres> <vres> <refresh> -rbt" -->
	<mode>
		<type>modeline</type>
		<alias>800x600_60</alias>
		<width>800</width>
		<height>600</height>
		<refresh>60</refresh>
		<value>35.500000  800 848 880 960  600 603 607 618  +HSync -VSync</value> <!-- 800x600x59.84 @ 36.979kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1024x768_60</alias>
		<width>1024</width>
		<height>768</height>
		<refresh>60</refresh>
		<value>56.000000  1024 1072 1104 1184  768 771 775 790  +HSync -VSync</value> <!-- 1024x768x59.87 @ 47.297kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1152x864</alias>
		<width>1152</width>
		<height>864</height>
		<refresh>60</refresh>
		<value>69.750000  1152 1200 1232 1312  864 867 871 889  +HSync -VSync</value> <!-- 1152x864x59.80 @ 53.163kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1280x800_60</alias>
		<width>1280</width>
		<height>800</height>
		<refresh>60</refresh>
		<value>71.000000  1280 1328 1360 1440  800 803 807 823  +HSync -VSync</value> <!-- 1280x800x59.91 @ 49.306kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1280x960_60</alias>
		<width>1280</width>
		<height>960</height>
		<refresh>60</refresh>
		<value>85.250000  1280 1328 1360 1440  960 963 967 988  +HSync -VSync</value> <!-- 1280x960x59.92 @ 59.201kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1280x1024_60</alias>
		<width>1280</width>
		<height>1024</height>
		<refresh>60</refresh>
		<value>91.000000  1280 1328 1360 1440  1024 1027 1031 1054  +HSync -VSync</value> <!--1280x1024x59.96 @ 63.194kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1400x900_60</alias>
		<width>1400</width>
		<height>900</height>
		<refresh>60</refresh>
		<value>86.500000  1400 1448 1480 1560  900 903 907 926  +HSync -VSync</value> <!-- 1400x900x59.88 @ 55.449kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1600x1200_60</alias>
		<width>1600</width>
		<height>1200</height>
		<refresh>60</refresh>
		<value>130.250000  1600 1648 1680 1760  1200 1203 1207 1235  +HSync -VSync</value> <!-- 1600x1200x59.92 @ 74.006kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1680x1050_60</alias>
		<width>1680</width>
		<height>1050</height>
		<refresh>60</refresh>
		<value>119.000000  1680 1728 1760 1840  1050 1053 1057 1080  +HSync -VSync</value> <!-- 1680x1050x59.88 @ 64.674kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1920x1080</alias>
		<width>1920</width>
		<height>1080</height>
		<refresh>60</refresh>
		<value>138.500000  1920 1968 2000 2080  1080 1083 1087 1111  +HSync -VSync</value> <!-- 1920x1080x59.93 @ 66.587kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>1920x1200</alias>
		<width>1920</width>
		<height>1200</height>
		<refresh>60</refresh>
		<value>154.000000  1920 1968 2000 2080  1200 1203 1207 1235  +HSync -VSync</value> <!-- 1920x1200x59.95 @ 74.038kHz !-->
	</mode>
	<mode>
		<type>modeline</type>
		<alias>2560x1600_60</alias>
		<width>2560</width>
		<height>1600</height>
		<refresh>60</refresh>
		<value>268.500000  2560 2608 2640 2720  1600 1603 1607 1646  +HSync -VSync</value> <!-- 2560x1600x59.97 @ 98.713kHz  !-->
	</mode>
</display>
