=== jappa/VizStack/share/schema/displayconfig.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.hp.com"
xmlns="http://www.hp.com"
elementFormDefault="qualified" >

<xs:element name="display">
	<xs:complexType>
		<xs:sequence>
			<!-- Mandatory name comes first. This is the dentifying name of the model. -->
			<xs:element name="model" type="xs:string" />

			<!-- 

			The type of input this display device takes by default. 
			If the device connectes using a digital interface, then use "digital". All flat panels will be by default digital.
			Digital interfaces are connected using either DVI-D or "DisplayPort". Avoid usage of DVI-I cables. This may make the GPU
			switch to using analog signals.
			If the device connects using a VGA cable, use "analog". All CRT displays are analog.
			-->
			<xs:element name="input" > 
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="digital" />
						<xs:enumeration value="analog" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<!-- 

			If you can get the EDID for this device, then use it here. Else be prepared to specify
			modelines

			-->
			<xs:element name="edid" minOccurs="0" maxOccurs="1" type="xs:string" />

			<!-- If you have the EDID bytes, feel free to use them too! -->
			<xs:element name="edidBytes" minOccurs="0" maxOccurs="1" type="xs:string" />

			<!-- This name should match the name exposed in the EDID -->
			<xs:element name="edid_name" type="xs:string" minOccurs="0" maxOccurs="1" />

			<xs:element name="hsync" minOccurs="0" maxOccurs="1" > <!-- If EDID is not specified, the sync value will be used from this -->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="min" type="xs:string" />
						<xs:element name="max" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="vrefresh" minOccurs="0" maxOccurs="1" > <!-- If EDID is not specified, the sync value will be used from this -->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="min" type="xs:string" />
						<xs:element name="max" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="dimensions" minOccurs="0" maxOccurs="1"> <!-- physical dimensions of the display -->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="width" type="xs:float" /> <!-- width in mm -->
						<xs:element name="height" type="xs:float" /> <!-- height in mm -->
						<xs:element name="bezel" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="left" type="xs:float" />
									<xs:element name="right" type="xs:float" />
									<xs:element name="bottom" type="xs:float" />
									<xs:element name="top" type="xs:float" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="default_mode" type="xs:string" /> <!-- The default mode to choose if none is specified. Must be in the list below -->

			<xs:element name="mode" minOccurs="0" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:sequence>
						<xs:element name="type" type="xs:string" />
						<xs:element name="alias" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
						<xs:element name="width" type="xs:nonNegativeInteger" />
						<xs:element name="height" type="xs:nonNegativeInteger" />
						<xs:element name="refresh" type="xs:nonNegativeInteger" />
						<xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="1" /> <!-- value depends on 'type'. Can be a modeline or empty at this point -->
						<xs:element name="bezel" minOccurs="0" maxOccurs="1"> <!-- per resolution bezel, in pixels -->
							<xs:complexType>
								<xs:sequence>
									<xs:element name="left" type="xs:nonNegativeInteger" /> <!-- note : all values in pixels. Any value specified here will override the computed bezel -->
									<xs:element name="right" type="xs:nonNegativeInteger" />
									<xs:element name="bottom" type="xs:nonNegativeInteger" />
									<xs:element name="top" type="xs:nonNegativeInteger" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== jappa/VizStack/share/templates/displays/Tridelity-MV2700.xml
<?xml version="1.0" ?>
<!--

VizStack display template for the Tridelity MV 2700 monitor.  This is Tridelity's
(http://www.tridelity.de/) auto-stereoscopic Multi-View 3D display.

Features : 27" screen, 5 3D views, Full HD resolution (1900x1200@60Hz), uses a 
Parallax barrier, with an optimal viewing distance of approx 8 feet.

This display is based on a Samsung SyncMaster monitor. Tridelity adds a special
mask over the display. 

Decoding the EDID yields

NVIDIA(0): -_- EDID for Samsung SyncMaster (DFP-0) -_-
NVIDIA(0): EDID Version                 : 1.3
NVIDIA(0): Manufacturer                 : SAM
NVIDIA(0): Monitor Name                 : Samsung SyncMaster
NVIDIA(0): Product ID                   : 666
NVIDIA(0): 32-bit Serial Number         : 1213542967
NVIDIA(0): Serial Number String         : HS8PC00564
NVIDIA(0): Manufacture Date             : 2007, week 51
NVIDIA(0): DPMS Capabilities            : Active Off
NVIDIA(0): Prefer first detailed timing : Yes
NVIDIA(0): Supports GTF                 : No
NVIDIA(0): Maximum Image Size           : 580mm x 360mm
NVIDIA(0): Valid HSync Range            : 30.0 kHz - 81.0 kHz
NVIDIA(0): Valid VRefresh Range         : 56 Hz - 75 Hz
NVIDIA(0): EDID maximum pixel clock     : 170.0 MHz

The default mode for this is 1920x1200 @ 60 Hz.  According to the EDID,
multiple other modes are supported as well, e.g.

1600 x 1200 @ 60 Hz
1280 x 1024 @ 60 Hz
1280 x 960  @ 60 Hz
1152 x 864  @ 75 Hz
640  x 480  @ 60 Hz
640  x 480  @ 72 Hz
640  x 480  @ 75 Hz
800  x 600  @ 56 Hz
800  x 600  @ 60 Hz
800  x 600  @ 72 Hz
800  x 600  @ 75 Hz
1024 x 768  @ 60 Hz
1024 x 768  @ 70 Hz
1024 x 768  @ 75 Hz
1280 x 1024 @ 75 Hz

However, the Tridelity screen supports 3D-viewing only at the Full HD 
resolution 1920x1200. So the other modes are omitted from this display's
definition.

-->

<display
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>Tridelity MV2700</model>
	<input>digital</input>
	<edid>/opt/vizstack/share/templates/displays/edids/Tridelity-MV2700.bin</edid>
	<edid_name>Samsung SyncMaster</edid_name>
	<default_mode>1920x1200_60</default_mode>
	<mode>
		<type>edid</type>
		<alias>1920x1200_60</alias>
		<alias>1920x1200</alias>
		<width>1920</width>
		<height>1200</height>
		<refresh>60</refresh>
	</mode>
</display>
