=== jappa/VizStack/share/schema/mouseconfig.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.hp.com"
xmlns="http://www.hp.com"
elementFormDefault="qualified" >

<xs:element name="mouse">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="type" type="xs:string" />
			<xs:element name="driver" type="xs:string" />
			<xs:element name="option" minOccurs="0" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" />
						<xs:element name="value" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== jappa/VizStack/share/templates/mouse/USBMouse.xml
<?xml version="1.0" ?>

<mouse 
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/mouseconfig.xsd">

		<type>USBMouse</type>
		<driver>mouse</driver>
		<option>
			<name>Protocol</name>
			<value>auto</value>
		</option>
		<option>
			<name>Emulate3Buttons</name>
			<value>no</value>
		</option>
		<option>
			<name>ZAxisMapping</name>
			<value>4 5</value>
		</option>
</mouse>
