=== jappa/VizStack/share/schema/resourcegroupconfig.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.hp.com"
xmlns="http://www.hp.com"
elementFormDefault="qualified" >

<xs:element name="resourcegroupconfig">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="resourceGroup" minOccurs="0" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" />
						<xs:element name="handler" type="xs:string" />
						<xs:element name="handler_params" type="xs:string" />
						<xs:element name="resources">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="reslist" minOccurs="1" maxOccurs="unbounded" >
										<xs:complexType>
											<xs:sequence>
												<xs:element name="res" minOccurs="1" maxOccurs="unbounded">
													<xs:complexType>
														<xs:choice>
															<xs:element name="gpu">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="hostname" type="xs:string" minOccurs="0" maxOccurs="1" />
																		<xs:element name="index" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
																	</xs:sequence>
																</xs:complexType>
															</xs:element>
															<xs:element name="server">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="hostname" type="xs:string" minOccurs="0" maxOccurs="1" />
																		<xs:element name="server_number" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
																	</xs:sequence>
																</xs:complexType>
															</xs:element>
														</xs:choice>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== jappa/VizStack/config/samples/resource_group_config.xml
<?xml version="1.0" ?>
<resourcegroupconfig
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/resourcegroupconfig.xsd" >

	<!-- Single Tile from Single GPU -->
	<resourceGroup>
		<name>test-1gpu-1node-1x1</name>
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,1];
			num_blocks=[1,1];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two horizontal Tiles from Single GPU -->
	<resourceGroup>
		<name>test-1gpu-1node-2x1</name>
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[2,1];
			num_blocks=[1,1];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two vertical Tiles from Single GPU -->
	<resourceGroup>
		<name>test-1gpu-1node-1x2</name>
		<handler>tiled_display</handler>
		<handler_params>	
			block_type="gpu";
			block_display_layout=[1,2];
			num_blocks=[1,1];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two vertical Tiles from Single GPU, each in portrait mode. This helps one watch a consistent image without rotating the displays -->
	<resourceGroup>
		<name>test-1gpu-1node-1x2-portrait</name> <!-- This does not work as expected -->
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,2];
			num_blocks=[1,1];
			display_device="LP2065";
			rotate="portrait";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from a single node, 2x1 -->
	<resourceGroup>
		<name>test-2gpu-1node-2x1</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,1];
			num_blocks=[2,1];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
				<res><gpu><index>1</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from a single node, 1x2 -->
	<resourceGroup>
		<name>test-2gpu-1node-1x2</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,1];
			num_blocks=[1,2];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
				<res><gpu><index>1</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from a single node, 1x2, portrait mode -->
	<resourceGroup>
		<name>test-2gpu-1node-1x2-portrait</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,1];
			num_blocks=[1,2];
			display_device="LP2065";
			rotate="portrait";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
				<res><gpu><index>1</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from two nodes, 2x1 -->
	<resourceGroup>
		<name>test-2gpu-2node-2x1</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,1];
			num_blocks=[2,1];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
			<reslist>
				<res><serverconfig><hostname>viz4.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from two nodes, 1x2 -->
	<resourceGroup>
		<name>test-2gpu-2node-1x2</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,1];
			num_blocks=[1,2];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
			<reslist>
				<res><serverconfig><hostname>viz4.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from two nodes, 1x2, portrait -->
	<resourceGroup>
		<name>test-2gpu-2node-1x2-portrait</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,1];
			num_blocks=[1,2];
			display_device="LP2065";
			rotate="portrait";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
			<reslist>
				<res><serverconfig><hostname>viz4.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from a single node, 2x2 -->
	<resourceGroup>
		<name>test-2gpu-1node-2x2</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[2,1];
			num_blocks=[1,2];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
				<res><gpu><index>1</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>
	<!-- Two GPUs from a single node, 2x2, xinerama -->
	<resourceGroup>
		<name>test-2gpu-1node-2x2-xinerama</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[2,1];
			num_blocks=[1,2];
			display_device="LP2065";
			combine_displays=True;
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
				<res><gpu><index>1</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from a single node, 4x1 -->
	<resourceGroup>
		<name>test-2gpu-1node-4x1</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[2,1];
			num_blocks=[2,1];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
				<res><gpu><index>1</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from a single node, 1x4, portrait -->
	<resourceGroup>
		<name>test-2gpu-1node-1x4-portrait</name>  <!-- portrait won't work for more with more than 1 displays per GPU -->
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,2];
			num_blocks=[1,2];
			display_device="LP2065";
			rotate="portrait";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
				<res><gpu><index>1</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from two nodes, 4x1 -->
	<resourceGroup>
		<name>test-2gpu-2node-4x1</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[2,1];
			num_blocks=[2,1];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
			<reslist>
				<res><serverconfig><hostname>viz4.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Two GPUs from two nodes, 2x2 -->
	<resourceGroup>
		<name>test-2gpu-2node-2x2</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[2,1];
			num_blocks=[1,2];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
			<reslist>
				<res><serverconfig><hostname>viz4.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>
	<!-- Two GPUs from two nodes, 1x4 -->
	<resourceGroup>
		<name>test-2gpu-2node-1x4</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,2];
			num_blocks=[1,2];
			display_device="LP2065";
		</handler_params>
		<resources>
			<reslist>
				<res><serverconfig><hostname>viz5.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
			<reslist>
				<res><serverconfig><hostname>viz4.ind.hp.com</hostname></serverconfig></res>
				<res><gpu><index>0</index></gpu></res>
			</reslist>
		</resources>
	</resourceGroup>

	<!-- Four GPUs from two nodes, 4x1 -->
	<resourceGroup>
		<name>test-4gpu-2node-4x1</name> 
		<handler>tiled_display</handler>
		<handler_params>
			block_type="gpu";
			block_display_layout=[1,1];
